### ISSUE TITLE
ASAP: Deploy at fairtracks.elixir.no/api/json2gsuite (same server as trackfind.elixir.no)

### ISSUE THREAD

**Issue by sveinugu** [elixir-no-nels/rest_gsuite#7]
If possible, deploy swagger docs at fairtracks.elixir.no/api, that contains this endpoint and "augment" (https://github.com/fairtracks/fairtracks_autogenerate_rest/issues/10).

**Comment by sveinugu** [comment]
To be used in application with deadline 31. jan (today)

**Comment by sveinugu** [comment]
Seems you went with my first suggestion fairtracks2gsuite, and not the second json2gsuite. Was that by mistake or by oversight?

**Comment by sveinugu** [comment]
Nice work, btw! :)

**Comment by dtitov** [comment]
That was a mistake... But I'll fix it.

**Comment by dtitov** [comment]
Done.
